version: 1.2.1.{build}
image: Visual Studio 2017
install:
  - cmd: nuget restore
assembly_info:
  patch: true
  file: AssemblyInfo.*
  assembly_version: "{version}"
  assembly_file_version: "{version}"
configuration: Release
before_build:
  - ps: Update-ModuleManifest -Path ./UncommonSense.PowerShell.TypeData/manifest.psd1 -ModuleVersion $env:APPVEYOR_BUILD_VERSION
build:
  verbosity: minimal
test_script:
  - ps: cd UncommonSense.PowerShell.TypeData/bin/$($env:CONFIGURATION); Write-Host $pwd; Get-ChildItem; Invoke-Pester
artifacts:
  - path: UncommonSense.PowerShell.TypeData/bin/$(configuration)