version: 1.2.1.{build}
image: Visual Studio 2017
install:
  - cmd: nuget restore
assembly_info:
  patch: true
  file: AssemblyInfo.*
  assembly_version: "{version}"
  assembly_file_version: "{version}"
configuration: Release
build:
  verbosity: minimal
artifacts:
  - path: bin/Release