version: 1.2.1.{build}
image: Visual Studio 2017
install:
  - cmd: nuget restore
assembly_info:
  patch: true
  file: AssemblyInfo.*
  assembly_version: "{version}"
  assembly_file_version: "{version}"
configuration: Release
build:
  verbosity: minimal
after_build:
  - ps: |
      $ManifestPath = ./UncommonSense.PowerShell.TypeData/bin/$($env:CONFIGURATION)/manifest.psd1
      Import-Module $ManifestPath -Force
      Update-ModuleManifest `
        -Path $ManifestPath `
        -ModuleVersion $env:APPVEYOR_BUILD_VERSION `
        -ExportedCmdlets (Get-Command -Module UncommonSense.PowerShell.TypeData -CommandType Cmdlet | Select-Object -ExpandProperty Name)
test_script:
  - ps: cd UncommonSense.PowerShell.TypeData/bin/$($env:CONFIGURATION); Invoke-Pester
artifacts:
  - path: UncommonSense.PowerShell.TypeData/bin/$(configuration)